spring:
  application:
    name: studentservice
  datasource:
    url: jdbc:mysql://localhost:3306/students_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        auto_quote_keyword: true
  sql:
    init:
      mode: always
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: size
        sort-parameter: sort

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
            extract: trace
